{
 "title": "Jenkins",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Executors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "default_jenkins_executors_busy", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Successful Builds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "default_jenkins_builds_failed_build_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}