apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.0.0
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-storage
          mountPath: /tmp/loki
      volumes:
      - name: loki-storage
        hostPath:
          path: /path/to/local/loki/data
          type: DirectoryOrCreate