pipeline {
    agent {
        kubernetes {
            label 'kubeagent'
        }
    }
    environment {
        DEPLOYMENT_TEMPLATE_PATH = 'Kubernetes/Web/web-deployment.yaml'
        MODIFIED_DEPLOYMENT_PATH = 'Kubernetes/Web/modified_web-deployment.yaml'
        VERSION_FILE = 'Kubernetes/Web/Docker/version.txt'
    }
    triggers {
        pollSCM('H/5 * * * *')
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/web']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        url: 'git@github.com:FerencSchmidt/StaticProject.git'
                    ]]
                ])
            }
        }
        stage('Agent Info') {
            steps {
                script {
                    echo "======================== START SECTION: AGENT INFO ========================"
                    echo "Build node: ${env.NODE_NAME}"
                    echo "Labels: ${env.NODE_LABELS}"

                    if (sh(script: "command -v kubectl", returnStatus: true) == 0) {
                        echo "kubectl is already installed."
                        sh "kubectl version --client"
                    } else {
                        echo "kubectl is not installed."
                    }
                    echo "======================== END SECTION: AGENT INFO ========================"
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    echo "======================== START SECTION: BUILD ========================"
                    sh "pwd"
                    sh "ls -lah"
                    sh "kubectl get pods -n jenkins"

                    if (fileExists(env.VERSION_FILE)) {
                        def versionTag = readFile(env.VERSION_FILE).trim()
                        echo "Version read from file: $versionTag"
                        
                        // Export variable for envsubst and perform substitution
                        sh """
                           export VERSION_TAG=${versionTag}
                           envsubst < ${env.DEPLOYMENT_TEMPLATE_PATH} > ${env.MODIFIED_DEPLOYMENT_PATH}
                        """
                        
                        echo "Deployment file has been updated with new tag: $versionTag"
                        sh "cat ${env.MODIFIED_DEPLOYMENT_PATH}"
                        sh "kubectl apply -f ${env.MODIFIED_DEPLOYMENT_PATH}"
                    } else {
                        error "version.txt file not found. Failing the build."
                    }
                    echo "======================== END SECTION: BUILD ========================"
                }
            }
        }
    }
    post {
        always {
            // Define any post-build actions here
            echo "Build completed."
        }
    }
}