apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # How often to scrape targets by default.
      evaluation_interval: 15s  # How often to evaluate rules.

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      # Scrape Node Exporter
      - job_name: node-exporter
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

      # Example: Add more targets here
      # Loki
      - job_name: loki
        static_configs:
          - targets: ['loki.monitoring.svc.cluster.local:3100']

      # Jenkins (via Prometheus plugin)
      - job_name: jenkins
        metrics_path: /prometheus
        static_configs:
          - targets: ['jenkins.monitoring.svc.cluster.local:8080']