apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  # How often to scrape targets by default.
      evaluation_interval: 15s  # How often to evaluate rules.

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: prometheus
        metrics_path: /prometheus/metrics  # Adjusted for the route prefix
        static_configs:
          - targets: ['localhost:9090']  # Internal Prometheus instance runs locally

      # Scrape Node Exporter (basic CPU, memory, disk metrics)
      - job_name: node-exporter
        metrics_path: /metrics
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']  # Matches node-exporter pod

      # Scrape Loki (logs metrics)
      - job_name: loki
        metrics_path: /metrics
        static_configs:
          - targets: ['loki.monitoring.svc.cluster.local:3100']  # Matches loki pod in "monitoring"

      # Scrape Jenkins (via Prometheus plugin)
      - job_name: jenkins
        metrics_path: /jenkins/prometheus  # Jenkins Prometheus plugin exposes metrics under '/prometheus' but we have the jenkins prefix also
        static_configs:
          - targets: ['jenkins-service.jenkins.svc.cluster.local:8080']  # Matches jenkins pod in "jenkins" namespace

      # Scrape kube-state-metrics (Kubernetes object state metrics)
      - job_name: kube-state-metrics
        metrics_path: /metrics
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']  # Matches kube-state-metrics pod in "monitoring"

      # Scrape NGINX Static Website (webapp-deployment pod)
      - job_name: nginx-exporter
        metrics_path: /metrics
        static_configs:
          - targets: ['nginx-prometheus-exporter.web.svc.cluster.local:9113']