apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab-runner
  name: gitlab-runner-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "delete", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "delete", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/attach", "pods/exec"]
    verbs: ["create", "get", "patch", "delete"]