apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
  namespace: web
spec:
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: nginx-prometheus-exporter