apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      initContainers:
      - name: install-plugins
        image: jenkins/jenkins:lts
        command: ['sh', '-c']
        args:
        - |
            jenkins-plugin-cli --plugins \
            kubernetes:4306.vc91e951ea_eb_d \
            kubernetes-cli:1.12.1 \
            kubernetes-credentials-provider:1.273.v15e69b_55ea_8e \
            git:5.7.0 \
            configuration-as-code:1932.v75cb_b_f1b_698d
        volumeMounts:
          - name: plugin-volume
            mountPath: /usr/share/jenkins/ref/plugins
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        env:
          - name: CASC_JENKINS_CONFIG
            value: /var/jenkins_home/casc_configs/jenkins.yaml
          - name: JENKINS_OPTS
            value: "--prefix=/jenkins --httpListenAddress=0.0.0.0"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: plugin-volume
          mountPath: /usr/share/jenkins/ref/plugins
        - name: ssh-keys
          mountPath: /var/jenkins_home/.ssh
          readOnly: true
        - name: casc-config
          mountPath: /var/jenkins_home/casc_configs
      volumes:
      - name: plugin-volume
        persistentVolumeClaim:
          claimName: jenkins-plugins-pvc
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home-pvc
      - name: ssh-keys
        secret:
          secretName: jenkins-ssh-keys
      - name: casc-config
        configMap:
          name: jenkins-config