apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Welcome to Jenkins configured via JCasC!"
      clouds:
        - kubernetes:
            name: "kubernetes"
            namespace: "jenkins"
            jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local:8080/jenkins"
            jenkinsTunnel: "jenkins-service.jenkins.svc.cluster.local:50000"
            templates:
              - name: "default-agent"
                label: "kubeagent"
                namespace: "jenkins"
                idleMinutes: 10
                volumes:
                - secretVolume:
                    mountPath: "/home/jenkins/.ssh"
                    optional: false
                    secretName: "ssh-key-secret"

    unclassified:
      location:
        url: "http://jenkins-service.jenkins.svc.cluster.local:8080"