apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-sa
      initContainers:
      - name: install-plugins
        image: jenkins/jenkins:lts
        command: ['sh', '-c']
        args:
        - |
            echo "Installing plugins"
            jenkins-plugin-cli --plugins \
            kubernetes:4306.vc91e951ea_eb_d \
            kubernetes-cli:1.12.1 \
            kubernetes-credentials-provider:1.273.v15e69b_55ea_8e \
            git:5.7.0 \
            configuration-as-code:1932.v75cb_b_f1b_698d \
            pipeline-model-definition:2.2236.va_b_88ceec798f \
            ssh-slaves:3.1031.v72c6b_883b_869 \
            github:1.42.0
        volumeMounts:
          - name: plugin-volume
            mountPath: /usr/share/jenkins/ref/plugins
      - name: job-configurator
        image: busybox
        command: ['sh', '-c']
        args:
        - |
            echo "Configuring jobs."
            echo "JENKINS_HOME = $JENKINS_HOME"
            mkdir -p /var/jenkins_home/jobs;
            for job_file in /config/*.xml; do
              job_name=$(basename "$job_file" .xml);
              mkdir -p "/var/jenkins_home/jobs/$job_name";
              cp "$job_file" "/var/jenkins_home/jobs/$job_name/config.xml";
              echo "Added $job_file to /var/jenkins_home/jobs/$job_name/config.xml."
            done
            echo "Setting permissions for jobs dir."
            chown -R 1000:1000 /var/jenkins_home/jobs;
            ls -lah /var/jenkins_home
            ls -lah /var/jenkins_home/jobs
        volumeMounts:
        - name: job-config
          mountPath: /config
        - name: jenkins-home
          mountPath: /var/jenkins_home
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        env:
          - name: CASC_JENKINS_CONFIG
            value: /var/jenkins_home/casc_configs/jenkins.yaml
          - name: JENKINS_OPTS
            value: "--prefix=/jenkins --httpListenAddress=0.0.0.0"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: plugin-volume
          mountPath: /usr/share/jenkins/ref/plugins
        - name: ssh-keys
          mountPath: /var/jenkins_home/.ssh
          readOnly: true
        - name: casc-config
          mountPath: /var/jenkins_home/casc_configs
      volumes:
      - name: plugin-volume
        persistentVolumeClaim:
          claimName: jenkins-plugins-pvc
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home-pvc
      - name: ssh-keys
        secret:
          secretName: jenkins-ssh-keys
      - name: casc-config
        configMap:
          name: jenkins-config
      - name: job-config
        configMap:
          name: jenkins-jobs