apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Welcome to Jenkins configured via JCasC!"
      clouds:
        - kubernetes:
            name: "kubernetes"
            namespace: "jenkins"
            jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local:8080/jenkins"
            jenkinsTunnel: "jenkins-service.jenkins.svc.cluster.local:50000"
            templates:
              - name: "Kubernetes-agent-template"
                label: "kubeagent"
                namespace: "jenkins"
                serviceAccount: "jenkins-sa"
                idleMinutes: 10
                containers:
                  - name: "jnlp"
                    image: "docker.io/library/jenkins-kubectl-agent"
                    workingDir: "/home/jenkins/agent"
                volumes:
                - secretVolume:
                    mountPath: "/home/jenkins/.ssh"
                    optional: false
                    secretName: "jenkins-ssh-keys"

    unclassified:
      location:
        url: "http://jenkins-service.jenkins.svc.cluster.local:8080"
