apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: monitoring
data:
  ds.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus.monitoring.svc.cluster.local:9090/prometheus
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      url: http://loki.monitoring.svc.cluster.local:3100
      basicAuth: false
      isDefault: false
      version: 1
      editable: false