apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: grafana-env
                key: GF_AUTH_ANONYMOUS_ENABLED
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            valueFrom:
              configMapKeyRef:
                name: grafana-env
                key: GF_AUTH_ANONYMOUS_ORG_ROLE
          - name: GF_FEATURE_TOGGLES_ENABLE
            valueFrom:
              configMapKeyRef:
                name: grafana-env
                key: GF_FEATURE_TOGGLES_ENABLE
          - name: GF_PATHS_PROVISIONING
            valueFrom:
              configMapKeyRef:
                name: grafana-env
                key: GF_PATHS_PROVISIONING
          - name: GF_SERVER_ROOT_URL
            valueFrom:
              configMapKeyRef:
                name: grafana-env
                key: GF_SERVER_ROOT_URL
        volumeMounts:
        - name: grafana-datasource-volume
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: true
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards/
        - name: grafana-dashboard-volume
          mountPath: /var/lib/grafana/dashboards/
      volumes:
      - name: grafana-datasource-volume
        configMap:
          name: grafana-datasource-config
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider
      - name: grafana-dashboard-volume
        configMap:
          name: grafana-click-count-dashboard
      restartPolicy: Always