{
 "title": "Jenkins",
 "refresh": "5s",
 "panels": [
  {
   "title": "Executors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    { "expr": "default_jenkins_executors_busy" }
   ]
  },
  {
   "title": "Successful Builds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "default_jenkins_builds_success_build_count_total"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "default_jenkins_builds_failed_build_count_total"
    }
   ]
  }
 ]
}