apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  labels:
    name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
          - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: log-volume
          mountPath: /var/log
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: log-volume
        hostPath:
          path: /var/log