apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: grafana/promtail:latest
        args:
          - -config.file=/etc/promtail/promtail.yaml
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: docker-containers
          mountPath: /var/lib/docker/containers
        - name: log-pods
          mountPath: /var/log/pods
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: docker-containers
        hostPath:
          path: /var/lib/docker/containers
      - name: log-pods
        hostPath:
          path: /var/log/pods